### ISSUE TITLE
Dont see much benefit using a keydb tls enabled cluster for latencies 

### ISSUE THREAD

**Issue by sangeethdba** [Snapchat/KeyDB#283]
**Describe the bug**
I dont see any benifit using keydb tls cluster  over redis 6.x tls  cluster in terms of latency improvements that keydb claiming
.intact p99 latencies  of redis 6.x cluster looks promising than keydb

** Log Files **

redis 6.x tls enabled cluster:

./memtier_benchmark --hide-histogram --tls --cert /opt/isv/redis/certfiles/newqpssc_certs/com-redis-cluster-qpssc.cer --key /opt/isv/redis/certfiles/newqpssc_certs/private.key -s cmqsrd00 -p 9001 --threads=32 --cacert=/opt/isv/redis/certfiles/newqpssc_certs/rootca.crt --cluster-mode             
                                                                                                             <
Writing results to stdout
[RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
[RUN #1 100%, 134 secs]  0 threads:    16000000 ops,  109980 (avg:  118931) ops/sec, 7.80MB/sec (avg: 8.43MB/sec), 41.50 (avg: 38.78) msec latencyyy

32        Threads
50        Connections per thread
10000     Requests per client

ALL STATS
======================================================================================================================================================
Type         Ops/sec     Hits/sec   Misses/sec    MOVED/sec      ASK/sec    Avg. Latency     p50 Latency     p99 Latency    p100 Latency       KB/sec
------------------------------------------------------------------------------------------------------------------------------------------------------
Sets        11184.06          ---          ---         0.00         0.00        41.38825         7.55100       733.18300       933.88700       861.62
Gets       111717.65    111717.65         0.00         0.00         0.00        32.66920         5.37500       659.45500       917.50300      8061.01
Waits           0.00          ---          ---          ---          ---             ---             ---             ---             ---          ---
Totals     122901.71    111717.65         0.00         0.00         0.00        33.46199         5.50300       667.64700       917.50300      8922.63

Key DB tls enabled cluster:
          
./memtier_benchmark --hide-histogram --tls --cert /opt/isv/redis/certfiles/newqpssc_certs/com-redis-cluster-qpssc.cer --key /opt/isv/redis/certfiles/newqpssc_certs/private.key -s cmqsrd00 -p 9003 --threads=32 --cacert=/opt/isv/redis/certfiles/newqpssc_certs/rootca.crt --cluster-mode                                                                                                       <
Writing results to stdout
[RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
[RUN #1 100%, 121 secs]  0 threads:    16000000 ops,  139138 (avg:  131499) ops/sec, 9.86MB/sec (avg: 9.32MB/sec), 32.15 (avg: 34.84) msec latency

32        Threads
50        Connections per thread
10000     Requests per client

ALL STATS
======================================================================================================================================================
Type         Ops/sec     Hits/sec   Misses/sec    MOVED/sec      ASK/sec    Avg. Latency     p50 Latency     p99 Latency    p100 Latency       KB/sec
------------------------------------------------------------------------------------------------------------------------------------------------------
Sets        12327.04          ---          ---         0.00         0.00        31.80614         4.76700       729.08700       942.07900       949.69
Gets       123134.97    123134.97         0.00         0.00         0.00        30.61775         4.60700       716.79900       937.98300      8884.81
Waits           0.00          ---          ---          ---          ---             ---             ---             ---             ---          ---
Totals     135462.01    123134.97         0.00         0.00         0.00        30.72582         4.60700       720.89500       937.98300      9834.50
$

keydb config:

cluster-enabled yes
cluster-config-file /opt/isv/redis/data/9002/nodes.conf
dir /opt/isv/redis/data/9002
pidfile /opt/isv/redis/run/node_9002.pid
logfile /opt/isv/redis/logs/node_9002.log
cluster-node-timeout 5000
#daemonize no
appendonly yes

# MAKE INTERFACE UNSECURE !!
protected-mode yes
bind XX>XX>XX>XX
timeout 0
tcp-keepalive 0
tcp-backlog 511
loglevel notice
syslog-enabled yes
syslog-ident redis_9002
syslog-facility USER
databases 16

# Snapshotting
save 900 1
save 300 10
save 60 10000
# Security
#requirepass C0mpl3x#1
# Limits
maxclients 10000
maxmemory-policy noeviction

# Append Only Mode
appendonly no
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

# Slow Log
slowlog-log-slower-than 10000
slowlog-max-len 128

# Advanced
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-entries 512
list-max-ziplist-value 64
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
activerehashing yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit slave 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
hz 10
aof-rewrite-incremental-fsync yes

#TLS config
port 0
tls-port 9002
tls-cluster yes
tls-replication yes

tls-cert-file /opt/isv/redis/certfiles/newqpssc_certs/com-redis-cluster-qpssc.com.cer
tls-key-file /opt/isv/redis/certfiles/newqpssc_certs/private.key
tls-ca-cert-file /opt/isv/redis/certfiles/newqpssc_certs/rootca.crt
server-thread-affinity true
server-threads 7

Please copy everything after this line.

**To Reproduce**

**Comment by sangeethdba** [comment]
@JohnSully

**Comment by sangeethdba** [comment]
@JohnSully  any help is appreciated

**Comment by JohnSully** [comment]
Hey @sangeethdba looking now.

**Comment by sangeethdba** [comment]
@JohnSully any help

**Comment by msotheeswaran** [comment]
Is there anyone still experiencing this issue, will be helpful to understand how to prioritize this.

**Comment by msotheeswaran** [comment]
Closing as there has been no response in 30 days
