### ISSUE TITLE
Install on FreeBSD error

### ISSUE THREAD

**Issue by Andrian-freebsd** [Snapchat/KeyDB#364]
Hi, please help me.
I’m trying to install KeyDB from git on the FreeBSD x64 12.2-Release, but I’m getting errors.
The first thing I would like to clarify is what dependencies need to be installed before assembly and installation KeyDB?
The documentation for ubuntu has such a list of dependencies:
build-essential, nasm, autotools-dev, autoconf, libjemalloc-dev, tcl, tcl-dev, uuid-dev, libcurl4-openssl-dev, git, but they are different for FreeBSD, so what exactly should be for FreeBSD?
Thank you!

**Comment by VivekSainiEQ** [comment]
Hi @Andrian-freebsd, 

What do the error messages look like?
