### ISSUE TITLE
[BUG] Multi-master node takes really long to recover after network break

### ISSUE THREAD

**Issue by JarmoSa** [Snapchat/KeyDB#367]
Tested the network disconnect with real size database and the result was really poor:
- 3 multi-master nodes, one way ring connections.
- nodes are connected with 100M link to each other, they are in separate datacenters
- using latest docker version: 6.2.0
- 2M keys / 4.5GB db in each node, nodes are up to date and all master / replica links are up
- some of the key values are somewhat large, up to 20MB, those are the main amount of data, but minority of the keys
- disconnected the vpn from one node to others for 5 minutes
- reconnected
- the disconnected node started to do full reload of all 4.5GB

=> it took 70 minutes before the node had catch up all the changes, about 1/3 of that time took the full reload of db (after that time the master link was shown as "up"), but 2/3 of the time was some processing - probably merging the data or something like that. Node was consuming about 20/30% average of one cpu during that time

Looks like keydb as it is now does not really work at all in multi-master mode with bigger databases. Even having static master-id values would not help with this problem as the full reload is done even while the master id of all nodes is still the same

I would expect the keydb to load only the changed data after such break and not do full reload. Also the recover/merge after actual data load should happen much faster

**Comment by alexanderGalushka** [comment]
@JarmoSa can you please share your configs

**Comment by JarmoSa** [comment]
@alexanderGalushka 
All three nodes have pretty standard keydb config files. Only these are non-default settings:
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 0 0 0
client-output-buffer-limit pubsub 128mb 32mb 60
masterauth "XXXXX"
requirepass XXXXX
multi-master yes
active-replica yes

and then each node is replica of next node, this is from keydb node 1:
replicaof keydb2.xxx 6379

**Comment by benschermel** [comment]
Hi @JarmoSa,

I would recommend trying the current unstable build. From [PR 371](https://github.com/EQ-Alpha/KeyDB/pull/371), partial sync is possible for active replication. This will help avoid full sync where possible. Build on the KeyDB 'unstable' branch, or if using docker, you can use the unstable tag (eqalpha/keydb:unstable). 

Adjusting `repl-backlog-size` and `client-output-buffer-limit replica` config parameters will assist with the amount of PSYNC possible.

**Comment by benschermel** [comment]
Closing this issue as Partial Synchronization support (PSYNC) is now shipped with version 6.3.1. Settings such as `repl-backlog-size` can be adjusted to avoid the need for a full sync.
