### ISSUE TITLE
Is there an open-ended load testing tool for keydb?

### ISSUE THREAD

**Issue by csbo98** [Snapchat/KeyDB#388]
Generally, we use memtier_benchmark to test keydb. However, memtier_benchmark is a close-ended tool. It only lanchs a new request when the completion of a previous request. That is not suitable for my test scenario. I want a open-ended load testing tool. I don't find such an open-ended testing tools, is there an open-ended load testing tool for keydb?

**Comment by msotheeswaran** [comment]
We do not have a tool for asynchronous benchmarking, however there are asynchronous redis client libraries you can use to test with KeyDB such as [boost_redis](https://github.com/boostorg/redis).
