### ISSUE TITLE
[BUG] deleted data comes back after restarting replica

### ISSUE THREAD

**Issue by paulandrewhughes** [Snapchat/KeyDB#390]
**Describe the bug**

When running in active-active mode with aof persistence, after deleting key from keydb and restarting the replica the deleted key is present again.

**To reproduce**

When running in active-active mode with 2 replicas with following configurations

user@b567db21f9b5:~/keydb/k1$ cat keydb_min.conf
bind 127.0.0.1
protected-mode no
port 6379
active-replica yes
replicaof 127.0.0.1 6378
daemonize no
pidfile /home/user/keydb/k1/keydb.pid
logfile /home/user/keydb/k1/keydb.log
dir /home/user/keydb/k1/
appendonly yes
appendfilename "appendonly.aof"
appendfsync always

user@b567db21f9b5:~/keydb/k2$ cat keydb_min.conf
bind 127.0.0.1
protected-mode no
port 6378
active-replica yes
replicaof 127.0.0.1 6379
daemonize no
pidfile /home/user/keydb/k2/keydb.pid
logfile /home/user/keydb/k2/keydb.log
dir /home/user/keydb/k2/
appendonly yes
appendfilename "appendonly.aof"
appendfsync always

127.0.0.1:6379> set foo bar
OK
127.0.0.1:6379> keys *
1) "foo"
127.0.0.1:6379> del foo
(integer) 1
127.0.0.1:6379> keys *
(empty array)

Press Ctrl-C replica on port 6378 cli 
tail the appendonly.aof file and see that del foo has been written to disk. 

127.0.0.1:6379> keys *
(empty array)

Start replica on port 6378 and key foo re-appears

127.0.0.1:6379> keys *
1) "foo"

**Expected behavior**

Deleted data should stay deleted.

**Additional information**

This was observed in v6.2.1 and v5.3.3
Compiled with gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)
This test was running on centos7.

**Comment by paulandrewhughes** [comment]
The problem also occurs in the current docker version

docker run -it --network=host -v /home/user/keydb/k1/keydb_min.conf:/etc/keydb/keydb.conf  --name k1  --mount type=bind,src=/home/user,target=/home/user  -d eqalpha/keydb
docker run -it --network=host -v /home/user/keydb/k2/keydb_min.conf:/etc/keydb/keydb.conf  --name k2  --mount type=bind,src=/home/user,target=/home/user  -d eqalpha/keydb


docker exec -ti k1 /usr/local/bin/keydb-cli
127.0.0.1:6379> set foo bar
OK
127.0.0.1:6379> keys *
1) "foo"
127.0.0.1:6379> del foo
(integer) 1

docker stop k2

127.0.0.1:6379> keys *
(empty array)

docker start k2

127.0.0.1:6379> keys *
1) "foo"

user@wsl2_ubuntu:~/keydb_test/k1$ docker exec -ti k1 /usr/local/bin/keydb-server --version
KeyDB server v=6.2.1 sha=5169f974:1 malloc=jemalloc-5.2.1 bits=64 build=4ae3a2af4279ea3c

**Comment by mtotone** [comment]
Hi,

I have the same issue on a Kubernetes cluster (keydb images: 6.2.2 and 6.3.0).

Did you figure it out ?

**Comment by paulandrewhughes** [comment]
Instead of deleting a key set it to a known value that your application understands means deleted with expiry in 3 days. 
Make sure before 3 days you have the append only file compacted.

**Comment by benschermel** [comment]
I just want to verify the sequence of events. Are you writing the value, stopping the replica (or disconnecting it), deleting the key, then restarting the replica?  If so it sounds like this is related to #447 #442. I did not see the issue when restarting replica following deleting the key (as nodes had synced already)

**Comment by mtotone** [comment]
> I just want to verify the sequence of events. Are you writing the value, stopping the replica (or disconnecting it), deleting the key, then restarting the replica? 

Yes, that's exactly what I did.

Thanks for the heads up.
