### ISSUE TITLE
it is possible to compile keydb with PGO?

### ISSUE THREAD

**Issue by osevan** [Snapchat/KeyDB#399]
How we can compile with gcc Keydb with pgo? 

First compile with -gcov -fprofile-generate? 

Running benchmarks and second compile with -fprofile-use and without !-gcov ?

Thanks and

Best regards

**Comment by msotheeswaran** [comment]
I would recommend running your use case instead of the benchmark, then the PGO will be specific to how you intend to use KeyDB. KeyDB benchmark only exercises a small subset of KeyDB's features so it may not provide the most relevant profile data to your use case.
