### ISSUE TITLE
Pro links in Wiki gives 404 and Pro checkout link is dead?

### ISSUE THREAD

**Issue by tmikaeld** [Snapchat/KeyDB#400]
Would be great if we could use the FLASH feature or buy the Pro version so we can use it.

What's the status here?

**Comment by solracsf** [comment]
I believe you should go to https://keydb.dev/keydb-enterprise/

**Comment by benschermel** [comment]
KeyDB FLASH will be publicly available Sept 2022 as an open source feature. KeyDB has joined Snap Inc and will be continuing with the open source project only, moving all previously Enterprise features to KeyDB Open Source. 

[Announcement of KeyDB Joining Snap](https://docs.keydb.dev/news/2022/05/12/keydb-joins-snap/)
[Roadmap](https://docs.keydb.dev/docs/coming-soon)

closing this issue as these pages are no longer available
