### ISSUE TITLE
[BUG] Building 6.3.0 on Raspberry PI fails

### ISSUE THREAD

**Issue by Talkabout** [Snapchat/KeyDB#416]
Hi,

trying to build version 6.3.0 on a Raspberry PI fails with this error:

![image](https://user-images.githubusercontent.com/10157917/168086313-335bd0a9-94c1-4297-b0ca-dd06c6481624.png)

**To reproduce**

Try to build on a Raspberry Pi

**Expected behavior**

Build succeeds on a Raspberry Pi

**Additional information**

**Comment by JohnSully** [comment]
32-bit cleanliness strikes again.  Should be a simple fix I'll take a look.

**Comment by Talkabout** [comment]
Thanks for the quick response John!

**Comment by Talkabout** [comment]
Hi @JohnSully ,

any news on this? Or is the fix more complex that you assumed?

Thanks!

**Comment by Talkabout** [comment]
Hi,

same issue with 6.3.1... any chance this gets fixed short term?

Thanks!

Bye

**Comment by QuintenQVD0** [comment]
yea please fix this! I have the same error on my pi with a 64 bit os: https://paste.gg/p/anonymous/d193e2860cc041eead84f998b7cf01c7

**Comment by Talkabout** [comment]
Hi @JohnSully,

you stated on May 12th that it is an easy fix. Unfortunately nothing happens till now. Can we expect do get this fixed in the next release version? Or is Raspberry Pi support officially dropped?

Thanks!

Bye

**Comment by msotheeswaran** [comment]
Closing as we are dropping support for 32 bit
