### ISSUE TITLE
[NEW] Support 'proxy protocol' to receive external IP's from haproxy

### ISSUE THREAD

**Issue by sigio** [Snapchat/KeyDB#455]
**Adding HAProxy's Proxy Protocol to get information about proxied connections**

This allows keydb to be ran behind a haproxy server, but still retain information about connecting clients.

https://www.haproxy.com/blog/use-the-proxy-protocol-to-preserve-a-clients-ip-address/

Protocol description:
https://github.com/haproxy/haproxy/blob/master/doc/proxy-protocol.txt

**Description of the feature**

Add support for Proxy protocol (v1 or v2)

**Alternatives you've considered**

None yet

**Additional information**

Should be relatively simple to implement, there are implementations in many daemons available already.

**Comment by JohnSully** [comment]
Is this something that is already available with HAProxy's Redis support? I admit I'm not super familiar with HAProxy but I know there are many people using it with KeyDB already.  See here: https://www.haproxy.com/blog/haproxy-advanced-redis-health-check/

**Comment by sigio** [comment]
I don't think so, so this might also be something for the redis github ;)

**Comment by JohnSully** [comment]
@sigio Closing because I don't see us having time to implement this ourselves as we don't use HAProxy is our stack, but we'd definitely accept a PR if someone in the community has time to do it.
