### ISSUE TITLE
[BUG] Unexpected reboot 

### ISSUE THREAD

**Issue by agosalvez** [Snapchat/KeyDB#457]
Hi, 

I use KeyDB (eqalpha/keydb:x86_64_v6.3.1) in a k8s cluster with 3 replicas.

I detail the initial command: 

`keydb-server /etc/keydb/redis.conf --active-replica yes --multi-master yes --appendonly no --bind 0.0.0.0 --port 6379 --protected-mode no --requirepass **************** --masterauth **************** --server-threads 2 --client-output-buffer-limit replica 512mb 512mb 0 --client-output-buffer-limit pubsub 512mb 512mb 0 '--replicaof keydb-1.keydb-headless 6379' '--replicaof keydb-2.keydb-headless 6379'`

During 15 days all was good but unexpected my 3 replicas were rebooted one by one and I don't know why. From this (5 days ago), KeyDB seems stable again.

I didn't modify or change any configuration since deployed.

I'll detail below with some pieces of log.

**Describe the bug**

I have 3 replicas (multi-master mode: on) that it worked fine 2 weeks but unexpectly, one replica (keydb-2), received a SIGNTERM signal: 

1:18:S 30 Jun 2022 07:55:51.929 * Background saving terminated with success
1:18:S 30 Jun 2022 08:00:52.053 * 10 changes in 300 seconds. Saving...
1:18:S 30 Jun 2022 08:00:52.054 * Background saving started
1:1539669:S 30 Jun 2022 08:00:57.299 * DB saved on disk
1:1539669:S 30 Jun 2022 08:00:57.317 * RDB: 1049 MB of memory used by copy-on-write
1:18:S 30 Jun 2022 08:00:57.404 * Background saving terminated with success
**1:signal-handler (1656576078) Received SIGTERM scheduling shutdown...**
1:18:S 30 Jun 2022 08:01:18.925 # User requested shutdown...
1:18:S 30 Jun 2022 08:01:18.925 * Saving the final RDB snapshot before exiting.
1:18:S 30 Jun 2022 08:01:24.054 * DB saved on disk
1:18:S 30 Jun 2022 08:01:24.054 * Removing the pid file.
1:18:S 30 Jun 2022 08:01:24.056 # KeyDB is now ready to exit, bye bye...`

keydb-0 and keydb-1 showed the next: (obviously because don't reach the keydb-2)

**keydb-0 and keydb-1**
1:19:S 30 Jun 2022 07:51:56.738 * Background saving terminated with success
1:19:S 30 Jun 2022 07:56:57.031 * 10 changes in 300 seconds. Saving...
1:19:S 30 Jun 2022 07:56:57.033 * Background saving started
1:1618071:S 30 Jun 2022 07:57:02.766 * DB saved on disk
1:1618071:S 30 Jun 2022 07:57:02.793 * RDB: 1267 MB of memory used by copy-on-write
1:19:S 30 Jun 2022 07:57:02.922 * Background saving terminated with success
**1:19:S 30 Jun 2022 08:01:24.199 # Connection with master lost.**
1:19:S 30 Jun 2022 08:01:24.199 * Caching the disconnected master state.
1:19:S 30 Jun 2022 08:01:24.199 # Connection with replica client id #17 lost.
1:19:S 30 Jun 2022 08:01:24.537 * Connecting to MASTER keydb-2.keydb-headless:6379
1:19:S 30 Jun 2022 08:01:24.595 * Unable to connect to MASTER: Resource temporarily unavailable
1:19:S 30 Jun 2022 08:01:25.609 * Connecting to MASTER keydb-2.keydb-headless:6379
1:19:S 30 Jun 2022 08:01:25.622 * Unable to connect to MASTER: Success
1:19:S 30 Jun 2022 08:01:26.643 * Connecting to MASTER keydb-2.keydb-headless:6379
1:19:S 30 Jun 2022 08:01:26.652 * Unable to connect to MASTER: Success
1:19:S 30 Jun 2022 08:01:27.660 * Connecting to MASTER keydb-2.keydb-headless:6379

When keydb-2 was working again, both replicas were connect successful with keydb-2
 
**keydb-0 and keydb-1**
1:19:S 30 Jun 2022 08:01:49.103 * Connecting to MASTER keydb-2.keydb-headless:6379
**1:19:S 30 Jun 2022 08:01:49.104 * MASTER <-> REPLICA sync started**
1:19:S 30 Jun 2022 08:01:49.104 * Non blocking connect for SYNC fired the event.
1:19:S 30 Jun 2022 08:01:49.105 * Master replied to PING, replication can continue...
1:19:S 30 Jun 2022 08:01:49.105 * Trying a partial resynchronization (request 68eacae75b5f9fd0034d505541f805e74ddb787b:31434846161).
1:19:S 30 Jun 2022 08:01:49.106 * Successful partial resynchronization with master.
1:19:S 30 Jun 2022 08:01:49.106 * MASTER <-> REPLICA sync: Master accepted a Partial Resynchronization.
1:19:S 30 Jun 2022 08:02:03.044 * 10 changes in 300 seconds. Saving...
1:19:S 30 Jun 2022 08:02:03.046 * Background saving started

20 minuts later, **keydb-1** received the same signal that received keydb-0 to finalize process.

**keydb-1**
1:19:S 30 Jun 2022 08:22:29.073 * Background saving started
1:1623901:S 30 Jun 2022 08:22:34.728 * DB saved on disk
1:1623901:S 30 Jun 2022 08:22:34.757 * RDB: 1259 MB of memory used by copy-on-write
1:19:S 30 Jun 2022 08:22:34.830 * Background saving terminated with success
1:signal-handler (1656577374) Received SIGTERM scheduling shutdown...
1:19:S 30 Jun 2022 08:22:55.032 # User requested shutdown...
1:19:S 30 Jun 2022 08:22:55.032 * Saving the final RDB snapshot before exiting.
1:19:S 30 Jun 2022 08:23:00.730 * DB saved on disk
1:19:S 30 Jun 2022 08:23:00.730 * Removing the pid file.

Keydb-0 repeated the regular process to reconnect keydb-1, but 20 minutes later of this, keydb-0 received the SIGNTERM too!!

**keydb-0**
1:28:S 30 Jun 2022 08:42:53.165 * Background saving terminated with success
1:signal-handler (1656578589) Received SIGTERM scheduling shutdown...
1:28:S 30 Jun 2022 08:43:09.930 # User requested shutdown...
1:28:S 30 Jun 2022 08:43:09.930 * Saving the final RDB snapshot before exiting.
1:28:S 30 Jun 2022 08:43:15.932 * DB saved on disk
1:28:S 30 Jun 2022 08:43:15.932 * Removing the pid file.
1:28:S 30 Jun 2022 08:43:15.977 # KeyDB is now ready to exit, bye bye...

I don't know why happened this, my cluster was working finde since 2 weeks ago without any problem. Sync between replicas was ok in every time.

Today, 5 days later of this, the cluster appears working fine.

Any can help me about this? Because I don't know why has ocurred this ....¿bug?

**To reproduce**

I don't know how can I reproduce this bug.

**Additional information**

Only in log of keydb-0 repeats this lines but without any transcendent:

NOTICE: Detuning locks due to high load per core: 136.60%
NOTICE: Detuning locks due to high load per core: 131.40%
NOTICE: Detuning locks due to high load per core: 141.53%
NOTICE: Detuning locks due to high load per core: 135.75%
NOTICE: Detuning locks due to high load per core: 150.37%
NOTICE: Detuning locks due to high load per core: 161.66%
NOTICE: Detuning locks due to high load per core: 170.48%
NOTICE: Detuning locks due to high load per core: 197.20%
NOTICE: Detuning locks due to high load per core: 208.72%

The consumes of memory and cpu were stables and regulars at the moment of replica's reboots 

Thank you in advance.

**Comment by JohnSully** [comment]
KeyDB is behaving as expected to the SIGTERM so this doesn't appear to be a server bug, but I have a few suggestions to debug your environment:

The detuning locks warning means that your machine is significantly oversubscribed (in terms of CPU consumption) you may need to either switch to a machine with more cores or reduce the load on the machine.  What is likely happening is that KeyDB is responding slowly due to the high load and your health checks have timed out.  The right fix is to reduce load on the box keydb-0 is running on.

**Comment by agosalvez** [comment]
Thank you!
