### ISSUE TITLE
[BUG] Keys command get wrong data randomly sometime

### ISSUE THREAD

**Issue by agosalvez** [Snapchat/KeyDB#458]
**Describe the bug**

The KEYS command works perfectly for me but sometime I've detected wrong data at the moment to get values. 

It seems that recover data of other key pattern.

It's very strange but in unlike redis, keydb uses multithreading architecture. It's possible that in a rare moment this command can fails?

**To reproduce**

It's random and does not depends on code.

**Additional information**

I use KeyDB (eqalpha/keydb:x86_64_v6.3.1) in a k8s cluster with 3 replicas.

Thank you in advance.

**Comment by JohnSully** [comment]
@agosalvez Can you be a little more specific? Is the data missing from a very recent write from a different client? You can try setting max-snapshot-slip to 0 to avoid this, it defaults to 400ms.

In 6.3 the keys command operates on a snapshot and runs in the background.  If we have a recent snapshot (up to max-snapshot-slip age) we will use it instead of making a fresh one.  This is also means other clients can execute writes while the keys command is running, those will not be returned.

**Comment by Kirkirillka** [comment]
@JohnSully I also encountered the similar problem.

Our traffic pattern is like:

- have 4-5 keys like `clicks:userid:groupid` with the structure: `{clickCounter: int, userId: str, groupid: str}`
- `userId` and `groupid` values are set with `HMSET`.
- `clickCounter` increased with `HINCRBY`.
- the keys updates frequently (150-300 rps)

There is a Redis cluster, one of KeyDB is also set up to replicate newest data from Redis.

In application we iterate over keys by pattern `clicks:*` with `KEYS clicks:*` command.

Periodically the returning keys are changing unexpectedly:

- ["clicks:user:1233", "clicks:user:1245", "clicks:user2341"]
- ["clicks:user:1233", "clicks:user:1245", "clicks:user2341"]
- ["clicks:user:1233", "clicks:user:1245", "clicks:user2341"]
- ["clicks:user:1233", "clicks:user:1245"]
- ["24124"]
- ["clicks:user:1233", "clicks:user:1245", "clicks:user2341"]
- [""]

Effectively, application uses the following sets of commands:

- HMSET
- HINCRBY
- GETALL
- KEYS
- DEL

When application connects to Redis, KeyDB nodes receives all data correctly. 

It seems KeyDB has dirty read and dirty writes [1](https://vladmihalcea.com/a-beginners-guide-to-read-and-write-skew-phenomena/). We also have the same application in UAT environment with KeyDB 3-4 rps, it has no such issues.
