### ISSUE TITLE
[BUG] TRIM MINID may delete messages whose IDs are higher than threshold 

### ISSUE THREAD

**Issue by paulmchen** [Snapchat/KeyDB#462]
NOTE: This is Redis 6.2 issue, the Redis community had fixed this issue and backported to Redis 6.2 release in Jan 2022. Here is the redis bug description : https://github.com/redis/redis/issues/9410  .  Here is the commit that fixes this problem:  https://github.com/redis/redis/pull/10068

@JohnSully  please merge the fix into KeyDB release. Thank you.

Describe the bug
In a certain scenario, the XTRIM command will delete messages with IDs higher than the threshold provided by the MINID option. In fact, all messages in the stream get deleted in this specific scenario.

To reproduce
One must add a message to the stream providing an ID, say "10-1". Then other messages must be added to the stream, but without providing an ID (using the "*" character).
If we call XTRIM passing one of the auto-generated IDs as the MINID, all messages in the stream will be deleted - even those with ID higher than the threshold provided.

For example:

reids:6379> scan 0
1) "0"
2) (empty array)
reids:6379> xadd mystream 10-1 key value
"10-1"
reids:6379> xadd mystream * key value
"1629903486170-0"
reids:6379> xadd mystream * key value
"1629903486920-0"
reids:6379> xadd mystream * key value
"1629903487256-0"
reids:6379> xadd mystream * key value
"1629903487544-0"
reids:6379> xread STREAMS mystream 0-0
1) 1) "mystream"
   2) 1) 1) "10-1"
         2) 1) "key"
            2) "value"
      2) 1) "1629903486170-0"
         2) 1) "key"
            2) "value"
      3) 1) "1629903486920-0"
         2) 1) "key"
            2) "value"
      4) 1) "1629903487256-0"
         2) 1) "key"
            2) "value"
      5) 1) "1629903487544-0"
         2) 1) "key"
            2) "value"
reids:6379> xtrim mystream MINID 1629903486920-0
(integer) 5
reids:6379> xread STREAMS mystream 0-0
(nil)

Note that all messages got removed from the stream.

Expected behavior
Only messages with IDs lower than 1629903486920-0 get removed. In this case, they would be 1629903486170-0 and 10-1.

Additional Information
Reproduced locally on a single redis node running as a container (imageId=ddcca4b8a6f0), redis_version=6.2.5.
I was also able to reproduce the problem using a java client (lettuce), so most likely this is not related to redis-cli.

**Comment by JohnSully** [comment]
Change 3a4f46104 pushed.

**Comment by paulmchen** [comment]
Thanks @JohnSully
