### ISSUE TITLE
Is it possible to downgrade from 6.3.1 to 6.2.2?

### ISSUE THREAD

**Issue by inakisoriamrf** [Snapchat/KeyDB#472]
Hi,

6.3.1 is completely [unusable and unstable](https://github.com/Snapchat/KeyDB/issues/460) with a high volume of keys. We are going to downgrade until it's fixed. Is it possible to downgrade node by node? 
I mean, disconnect one node, downgrade, add to the cluster and wait for sync and go for the next node.

Thanks

**Comment by agosalvez** [comment]
Yes, sorry, Ai read after posted. Thanks

**Comment by padinko** [comment]
Hi,
I downgraded 3 servers today because of #453 

i just need to comment in config this line:
```
replica-weighting-factor 2
```
because it does not exists in 6.2.2

I have installed it by their official PPA;
```bash
apt update
apt-cache madison keydb # to list all available versions
apt install keydb=6:6.2.2-1~bionic1 keydb-server=6:6.2.2-1~bionic1 keydb-tools=6:6.2.2-1~bionic1 # update versions by your server build version
```

**Comment by JohnSully** [comment]
Sorry 6.3 isn't working well for you.  6.2.x will continue to be maintained until we meet expectations.

**Comment by oxy-arnoldasb** [comment]
Similarly with debian10
```
apt-get install keydb=6:6.2.2-1+deb10u1 keydb-sentinel=6:6.2.2-1+deb10u1 keydb-server=6:6.2.2-1+deb10u1 keydb-tools=6:6.2.2-1+deb10u1
```

**Comment by Diz-X** [comment]
Hopefully we get an update soon, because the 6.3.1 is not working very well...
