### ISSUE TITLE
2 DC and 3DC Reference Architecture

### ISSUE THREAD

**Issue by aarvee11** [Snapchat/KeyDB#476]
Dear All,

it’s a humble request to learn from the community on what is the best/reference architecture for 2 Data Centers and 3 Data Centers deployment in order to achieve the best resiliency for any given gig performing OLTP applications.

Consider we today handle close to 4 Billion API calls in 24 hours and have 2 Data Centers and we are eventually moving into 3 Data Centers with an Active-Active Multi-Master Arch.

Support will be highly appreciated!

Thank You

**Comment by j13tw** [comment]
Our team currently maintains and operates two dual data centers
(Build with Kuberntes and used Istio Service Mesh)
The following methods may be for your reference

We used Kubernetes StatefulSet replica 3 in per DC
and create a Service to Mapping another Side DC
the DC_A  replicaof will include their 3 replica and the DC_B Service 
(connect to DC_B, and connected its 3 Replica any one)
and the DC_B also replica itself 3 Replica and DC_A Service

I think, In this replicaof setup for keydb
When the Keydb Server on DC_A Syncing
It will trigger Sync DC_B Server,
and DC_B will also trigger interval Server Syncing 

By the way, we use the keydb helm chart deploy 
it can disable replicaof self server on starting time
so you can scale your keydb server on update helm chart
and just needed protect your other DC replica setting
if you have more DC will replicaof server
you can add the replicaof server under the another DC_LB

```
Like this Setting

DC_A:
---
DC_A_0: DC_A_1, DC_A_2, DC_B_LB 
DC_A_1: DC_A_0, DC_A_2, DC_B_LB
DC_A_2: DC_A_0, DC_A_1, DC_B_LB

DC_B: 
---
DC_B_0: DC_B_1, DC_B_2, DC_A_LB
DC_B_1: DC_B_0, DC_B_2, DC_A_LB
DC_B_2: DC_B_0, DC_B_1, DC_A_LB

===
if DC_C joined
DC_C_0: DC_A_LB, DC_B_LB
and add the DC_C_LB after the  DC_A_LB, DC_B_LB 
```

Finally, our data and connect test 
the architecture are not testing with high performance of large concurrency
we just facing dual DC Connectivity Sync Cache
So, I strongly recommended build and Testing before online
