### ISSUE TITLE
[NEW] KeyDB FLASH Support - release date 

### ISSUE THREAD

**Issue by raphaelauv** [Snapchat/KeyDB#490]
`Support for KeyDB FLASH using the RocksDB engine will become available September 2022`

do you still plan to release this month the RocksDB engine  ? thanks

**Comment by agosalvez** [comment]
Hi, @JohnSully can we know anything about this? Thanks!

**Comment by pr4u4t** [comment]
I'm also interested in this I can add leveldb support, rocksdb can act as example. I found some files indicating rocksdb support but since you're planning release of rocksdb support I don't see a reason of implementing it on my own.

**Comment by benschermel** [comment]
We are currently planning on introducing this to the unstable (Main) branch on Friday (Sept 30) where you can view/build/try. We will publish this to the Docker 'unstable' image at that time as well.

We will be planning a larger 6.4 release at a later date which will include the FLASH build in all distributions.

**Comment by benschermel** [comment]
Hi Folks, sorry for the delay, we are waiting on a final validation but hope to have this out in the next few days :) We will keep you posted as soon as soon as its available

**Comment by jiangsi** [comment]
I'm really looking forward to this version, which will allow me to save a lot of data on disk instead of in memory

**Comment by pr4u4t** [comment]
> It's much more powerfull to use nvme 2.0 's key value storage interface than RocksDB. Hope there be such a version in future.

As stated in [specification](https://www.snia.org/sites/default/files/ESF/Key-Value-Storage-Standard-Final.pdf) nvme key-value storage is implemented in RocksDB compatible library see page 27. I'm willing to do this as I'm in need all I'm waiting is flash storage to be available.

**Comment by yangkequn** [comment]
always use nvme 2.0 key-value storage. 
It cut down disk io to 1/6, compared with other db according to samsung's early study.
It reduce flash write amplification to 1.0, while redis rdb has a  write  amplification ratio over 1000.
It's fast, typically, it can provide more than 2M+ iops with lowest latency. Some studies shows one nvme key-value disk can relace 50 xeon kernels that running rocksdb, using about 1/100 power and zero system memory.
it never lost data,once data send to disk. 
It won't create a db file like rocksdb which always expanding its size, and awkward to shrink size. 
It's cheap and easy available when time comes to 2023.

**Comment by JohnSully** [comment]
Just a heads up the code is out in the OSS_RELEASE_SEP branch. @benschermel will be prepping the release images. 

To avoid a repeat of problems with 6.3 even though this has been deployed successfully with customers in the past we will mark the flash feature as Beta.

**Comment by JohnSully** [comment]
By the way integrating with Snap has been a learning experience and I’ve gained a bigger appreciation for the issues on the control plane side. I apologize for how much time this has taken with me away from the project.

**Comment by pr4u4t** [comment]
@JohnSully @benschermel Great thanks I'll proceed with flash testing and adding nvme support.

**Comment by dokterbob** [comment]
@yangkequn @pr4u4t Very interesting this native NVMe K/V. It seems a different issue though, but wow what a potential!

**Comment by tsiege** [comment]
Any news on this?

**Comment by raphaelauv** [comment]
https://github.com/Snapchat/KeyDB/releases/tag/v6.3.2
