### ISSUE TITLE
Is KeyDB v6.3.1 stable ?

### ISSUE THREAD

**Issue by silviucpp** [Snapchat/KeyDB#494]
Hello,

I see lot of issues opened and users complaining on version 6.3.1 and no clarification on them. So is this version stable and safe to upgrade or we should stick with 6.2.2 ?

Silviu

**Comment by Diz-X** [comment]
We have been using it, and it has a really big issue. I would donwgrade to 6.2.2 as it is unstable, and after couple of months still no release with batch for the big issues it is having.

**Comment by Diz-X** [comment]
> I would suggest self-compile the latest `main` as some bad bugs had been fixed since 6.3.1 _(but yeah, no official release yet)_.
> See [v6.3.1...main](https://github.com/Snapchat/KeyDB/compare/v6.3.1...main)

It amazes me that they haven't released a version 6.3.2 with these fixes. It gives me a really bad taste about the future and dedication of this project.

**Comment by fannyfan414** [comment]
> The problem is we started building a bunch of control plane items to handle larger workloads at Snap and it’s taken a lot more energy than I anticipated.
> 
> We are planning to open source this as well but I want it to be more controlled than 6.3 was so we don’t have a repeat.

Any news for 6.3.2?

**Comment by DreadfulCode** [comment]
The answer is **No, 6.3.1 is NOT stable.**
It inexplicably fails when you least expect it, although when ran as systemd unit, it will appear to be enabled and working.

KeyDB v6.2.2 IS stable, however.

**Comment by msotheeswaran** [comment]
v6.3.2 is out and has quite a few fixes, 6.3.3 will be coming in the next month with more.
