### ISSUE TITLE
[BUG] -flto gcc works now? 

### ISSUE THREAD

**Issue by osevan** [Snapchat/KeyDB#510]
In my previos setup from 6 month ago,  i couldnt compile keydb with gcc -flto, because compiled application binary doesnt start.

How we can solve this? 

Any solutions? 

Thanks and

Best regards...

**Comment by msotheeswaran** [comment]
KeyDB already compiles with -flto by default: https://github.com/Snapchat/KeyDB/blob/main/src/Makefile#L22
