### ISSUE TITLE
community.keydb.dev Lets Encrypt certificate expired

### ISSUE THREAD

**Issue by IBG-Projects** [Snapchat/KeyDB#511]
Just caught my eye because Google redirects to the subdomain.

Expired on: Wed, 05 Oct 2022 14:53:27 GMT
https://community.keydb.dev

#464
It can't really make sense to manually renew the certificate every 3 months...

@JohnSully @benschermel

**Comment by benschermel** [comment]
Thanks for the callout, it is renewed. The container is renewing certs automatically however host is still needing the service restarted. I have it as a backlog item to fix
