### ISSUE TITLE
[BUG] `repl-diskless-sync yes` does not actually enable diskless replication

### ISSUE THREAD

**Issue by danog** [Snapchat/KeyDB#513]
**Describe the bug**

A thing I noticed when debugging https://github.com/Snapchat/KeyDB/issues/512, setting `repl-diskless-sync yes` in the config doesn't actually enable diskless replication, because the logs contain `MASTER <-> REPLICA sync: receiving streamed RDB from master with EOF to disk` logs instead of `MASTER <-> REPLICA sync: receiving streamed RDB from master with EOF to parser` logs, and a temporary rdb file gets created in the rdb directory.

**To reproduce**

As per https://github.com/Snapchat/KeyDB/issues/512

Same config as in #512:
```
protected-mode no
tcp-backlog 511
timeout 600
tcp-keepalive 300
supervised no
loglevel notice
databases 16
always-show-logo yes
lazyfree-lazy-eviction no
lazyfree-lazy-expire no
lazyfree-lazy-server-del no
replica-lazy-flush no
lua-time-limit 5000
slowlog-log-slower-than 10000
slowlog-max-len 128
latency-monitor-threshold 0
notify-keyspace-events ""
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-size -2
list-compress-depth 0
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
hll-sparse-max-bytes 3000
stream-node-max-bytes 4096
stream-node-max-entries 100
activerehashing yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 0 0 0
client-output-buffer-limit pubsub 32mb 8mb 60
hz 10
dynamic-hz yes

repl-diskless-sync yes
repl-diskless-sync-delay 5
repl-disable-tcp-nodelay no

save ""
appendonly no

server-threads 8
maxclients 100000
maxmemory 2Gb
maxmemory-policy noeviction

replica-serve-stale-data yes
replica-read-only no
active-replica yes
multi-master yes
```

**Expected behavior**

No files get created.

**Additional information**

Same logs contained in https://github.com/Snapchat/KeyDB/issues/512

**Comment by msotheeswaran** [comment]
There is a "repl-diskless-load" config you need to set on the replicas as well, it can be one of "disabled", "on-empty-db", or "swapdb". When "disabled" the replica will write the received rdb to disk first, when "on-empty-db" it will be diskless only if the replica is empty, when "swapdb" the new rdb will be read into memory then swapped with the existing db.

**Comment by danog** [comment]
Thanks, `swapdb` seems to avoid writing to disk files, according to the logs.
