### ISSUE TITLE
[BUG] flushall async took 60 seconds in flash use case when the redis.conf configures 256 databases

### ISSUE THREAD

**Issue by paulmchen** [Snapchat/KeyDB#516]
**flushall async took 60 seconds in SSD use case when the redis.conf configures 256 databases**

When we configure 256 databases in redis.conf and run with the storage provider use case, the flushall async command takes 60 seconds to complete.

**To reproduce**

1. Set the following parameters in the configuration:

   databases 256
   storage-provider flash /root/data

2. Start the server
3. Run "flushall async"  from the cli command line
4. The command takes 60 seconds to complete 

**Expected behavior**

It should take less time to "flushall async" even though the number of databases configured is 256.

**Additional information**

**Comment by paulmchen** [comment]
Here is a workaround fix https://github.com/Snapchat/KeyDB/commit/fb0c8e475f02d1391ab5e93af68745e2fbee34f1

**Comment by msotheeswaran** [comment]
Fix released with 6.3.2, thanks @paulmchen!
