### ISSUE TITLE
KeyDB performance factors

### ISSUE THREAD

**Issue by Ankita-020696** [Snapchat/KeyDB#517]
Hi,
I am newbie to KeyDB.
I have executed keydb using keydb-benchamrk -n 1000000 on different boards on RISCV arch. I see difference in results of all.
What parameters/factors I should check to find out the reason of difference?

Thanks

<div ccp_infra_version='3' ccp_infra_timestamp='1669810432752' ccp_infra_user_hash='1242408818' ccp_infra_copy_id='a3634861-cf47-4877-82dd-baacfcb775c8' data-ccp-timestamp='1669810432752'><html><head><meta name=ProgId content=Excel.Sheet><meta name=Generator content="Microsoft Excel 15"><style>table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	text-align:general;
	vertical-align:bottom;
	border:none;
	white-space:nowrap;
	mso-rotate:0;}
.xl19
	{font-weight:700;
	vertical-align:middle;}
</style></head><body link="#0563C1" vlink="#954F72">

SET | 79.39 | 1284.04 | 244.26 | 213.53
-- | -- | -- | -- | --
GET | 81.03 | 1170.26 | 240.64 | 210.84
LPUSH | 123.98 | 1279.94 | 251.09 | 216.23
LPOP | 78.92 | 1365.09 | 244.36 | 215.35
SADD | 81.8 | 1305.66 | 242.43 | 209.44

</body></html></div>

**Comment by DreadfulCode** [comment]
The library, keydb-benchark, is a fork of redis-benchmark, which only targets one CPU. So if you are benchmarking a KeyDB install running on multiple threads, you will have to multiply the result by the # of server-threads used.

Being a multithreaded fork of Redis, KeyDB is better measured with memtier benchmark, which will give you the bigger picture. For more info, please check the KeyDB documentation: https://docs.keydb.dev/docs/benchmarking/
