### ISSUE TITLE
Forkless backup and `maxmemory`

### ISSUE THREAD

**Issue by air3ijai** [Snapchat/KeyDB#526]
Hello,

I'm just trying to prepare a guide how to configure memory on KeyDB Multi-Master configuration and probably found some  discrepancy.

 The main point is [Forkless Background Saving](https://docs.keydb.dev/docs/mvcc/#forkless-background-saving).

 And two additional reference in the documentation
 1. [KeyDB setup hints](https://docs.keydb.dev/docs/intro-admin/#keydb-setup-hints)
    > Set an explicit maxmemory option limit in your instance in order to make sure that the instance will report errors instead of failing when the system memory limit is near to be reached. Note that maxmemory should be set calculating the overhead that KeyDB has, other than data, and the fragmentation overhead. So if you think you have 10 GB of free memory, set it to 8 or 9.

 2. [Selecting RAM, FLASH & Machine Size](https://docs.keydb.dev/docs/flash-sizing/#selecting-ram-flash--machine-size)
    > We recommend allocating 50% of memory (maxmemory setting) towards data and up to 70% if you allocate a swap space similar in size. This allows space for system operations as well as up to 30% that may be allocated during BGSAVE during heavy write loads.

 Maybe the second only is just for *KeyDB on FLASH* or maybe one of the reference should be updated?

 Which value should we consider to use for node with the 8 GB of RAM and without swap configured?
 ```
 maxmemory 6500mb
 maxmemory 4000mb
 ```

**Comment by msotheeswaran** [comment]
Hello @air3ijai,
The key is if forkless background saving is enabled or not,
with forkless saving you can use "maxmemory 6500mb" based on the guidance from 1.
without forkless saving I would recommend "maxmemory 4000mb" as described in 2., this is due to the potential overhead from forking (theoretical worst case of 2x memory usage during the fork).

**Comment by air3ijai** [comment]
Hello @msotheeswaran, thank you for the clarifications !

As I see forkless background saving is enabled on KeyDB Pro version. It is just about version or any specific configuration key?

How we can check if it is enabled?

**Comment by msotheeswaran** [comment]
There is a "use-fork" config you can set to "yes" to enable forking and "no" to use forkless saving. By default it is "no".

**Comment by air3ijai** [comment]
It is save to use it? I mean, if it is an advantage, why not to enable it by default?

Or it is a kind of experimental feature?

**Comment by msotheeswaran** [comment]
forkless saving is the new feature, this config is to force the old behaviour, which is why it is disabled by default.
