### ISSUE TITLE
[BUG] Redisearch with ENABLE_FLASH=yes

### ISSUE THREAD

**Issue by keithchew** [Snapchat/KeyDB#531]
**Describe the bug**

When using KeyDB with flash, upon startup/restart, redisearch indexes are not created/initialised/loaded. I believe that the current redisearch module starts the indexing process when data is loaded into memory from RDB, and in the case of flash, this step is not performed as data is kept flash. Would like to know if there is a workaround on startup to kick off the indexing process from flash.

**To reproduce**

- Create new DB
- Create new search index
- Add search data
- Confirm search works
- Restart KeyDB
- Search stops working

**Expected behavior**

When flash is enabled, KeyDB should initialise search indexes into memory on startup.

**Comment by msotheeswaran** [comment]
We are unable to officially support usage of redisearch with keydb, but we will continue to fix any bugs with the module api.
