### ISSUE TITLE
Active-active multimaster without rdb and aof

### ISSUE THREAD

**Issue by fannyfan414** [Snapchat/KeyDB#542]
Is it safe to use keydb in active-active mode without any rdb/aof backup?

Do I understand correctly that in this case the data is duplicated on two masters, and if one breaks, then the second one will save the data and continue to work correctly?

Or if one master breaks, then restarts, then it can delete / break data from the second (healthy) master?

**Comment by air3ijai** [comment]
[Using Multiple Masters](https://docs.keydb.dev/docs/multi-master/)
> When KeyDB connects with multiple masters it behaves differently than with traditional replication:
>
>    - Multiple invocations of the replicaof command will result in adding additional masters, not replacing the current one
>    - KeyDB will not drop its database when sync'ing with the master
>    - KeyDB will merge any reads/writes from the master with its own internal database
>    - KeyDB will default to last operation wins
>
> This means that a replica with multiple masters will contain a superset of the data of all its masters. If two masters have a value with the same key it is undefined which key will be taken. If a master deletes a key that exists on another master the replica will no longer contain a copy of that key.

1. After failed master will start again it will not contain any data and will start to sync data from the health one.
2. The health master will not be affected because
     - > KeyDB will not drop its database when sync'ing with the master
     - > KeyDB will merge any reads/writes from the master with its own internal database

**Comment by air3ijai** [comment]
> Is it safe to use keydb in active-active mode without any rdb/aof backup?

It is generally safe but you should be ready to loose all your data :)
If both nodes will restart during short period of time which will not permit a cross-sync - you will get a clean DB.


> Do I understand correctly that in this case the data is duplicated on two masters, and if one breaks, then the second one will save the data and continue to work correctly?

Yes, every node follow another one and have superset of all the data - with possible short drift because by default replication is async, but your can change that and should be ready for the performance penalty.

Do not forget, that balancing and failover to another node is done by some external layer - your app connection string, HAProxy, Nginx and etc.

**Comment by air3ijai** [comment]
I didn't use that but probably it can be found in the documentation, for example here - [Default Configuration File](https://docs.keydb.dev/docs/config-file#default-configuration-file).

It maybe the case that you should consider to run at least 3 nodes and in case that one node is down, two other will act as read-write - otherwise, in case of two nodes, the health one may be blocked until the second master is returned back.
```
# Master-Replica replication. Use replicaof to make a KeyDB instance a copy of
# another KeyDB server. A few things to understand ASAP about KeyDB replication.
#
#   +------------------+      +---------------+
#   |      Master      | ---> |    Replica    |
#   | (receive writes) |      |  (exact copy) |
#   +------------------+      +---------------+
#
# 1) KeyDB replication is asynchronous, but you can configure a master to
#    stop accepting writes if it appears to be not connected with at least
#    a given number of replicas.
# 2) KeyDB replicas are able to perform a partial resynchronization with the
#    master if the replication link is lost for a relatively small amount of
#    time. You may want to configure the replication backlog size (see the next
#    sections of this file) with a sensible value depending on your needs.
# 3) Replication is automatic and does not need user intervention. After a
#    network partition replicas automatically try to reconnect to masters
#    and resynchronize with them.
#
# replicaof <masterip> <masterport>
```
```
# When a replica loses its connection with the master, or when the replication
# is still in progress, the replica can act in two different ways:
#
# 1) if replica-serve-stale-data is set to 'yes' (the default) the replica will
#    still reply to client requests, possibly with out of date data, or the
#    data set may just be empty if this is the first synchronization.
#
# 2) if replica-serve-stale-data is set to 'no' the replica will reply with
#    an error "SYNC with master in progress" to all the kind of commands
#    but to INFO, replicaOF, AUTH, PING, SHUTDOWN, REPLCONF, ROLE, CONFIG,
#    SUBSCRIBE, UNSUBSCRIBE, PSUBSCRIBE, PUNSUBSCRIBE, PUBLISH, PUBSUB,
#    COMMAND, POST, HOST: and LATENCY.
#
replica-serve-stale-data yes
```

```
# It is possible for a master to stop accepting writes if there are less than
# N replicas connected, having a lag less or equal than M seconds.
#
# The N replicas need to be in "online" state.
#
# The lag in seconds, that must be <= the specified value, is calculated from
# the last ping received from the replica, that is usually sent every second.
#
# This option does not GUARANTEE that N replicas will accept the write, but
# will limit the window of exposure for lost writes in case not enough replicas
# are available, to the specified number of seconds.
#
# For example to require at least 3 replicas with a lag <= 10 seconds use:
#
# min-replicas-to-write 3
# min-replicas-max-lag 10
#
# Setting one or the other to 0 disables the feature.
#
# By default min-replicas-to-write is set to 0 (feature disabled) and
# min-replicas-max-lag is set to 10.
```

**Comment by air3ijai** [comment]
How do you balance traffic to your Sentinel?

Your app contact first Sentinel to ask for the current Master.
If Sentinel-1 is down - how your app will connect to the Sentinel-2, or you just put all 3 Sentinel nodes in the app config?

In case of KeyDB you can place a Load Balancer in front of KeyDB Multi-Master

```
                  KeyDB-1
                /     |
App --> HAProxy       |
                \     |
                  KeyDB-2
```

You can configure how traffic is balanced. Examples of the strategies
1. Balance with sticky session by source IP
2. Primary and Standby


> But if replication is asynchronous

1. How your current Redis is configured, it is a sync replica?
2. What is happen when failover occur, are you sure that you have same data on replica?
3. How long failover take?

**Comment by air3ijai** [comment]
Just to recap your current (Redis) and possible (KeyDB) options

#### Current - Redis
1 x Sentinel Proxy
3 x Redis + Sentinel

#### Possible - KeydB
1 x HAProxy
2 x KeyDB

1. With default Sentinel settings using [Bitnami Chart](https://github.com/bitnami/charts/tree/main/bitnami/redis) my tests shown that when Master goes down for ~ 1 minutes, Sentinel didn't failover to the new one. Sure it can be tuned and tested.
2. I don't know exactly how Redis Sync working - [Important facts about Redis replication](https://redis.io/docs/management/replication/#important-facts-about-redis-replication)
    > Redis uses asynchronous replication, with asynchronous replica-to-master acknowledges of the amount of data processed.

It is important in our case to get rid of such a part like Sentinel and have a fast failover. Related to the performance - Redis 7 probably get us more speed, but is should be tested more detailed.

**Comment by air3ijai** [comment]
> Maybe for keydb exists such tool as proxysql (max scale) for MySQL/Mariadb multi master, that can route “write/lock/delete” request to one master, but reads can be from all masters

[comment](533#issuecomment-1376466025)
> @JohnSully has been working on a new proxy server for KeyDB which he will be able to talk about soon along with a further roadmap

Maybe this one?

**Comment by msotheeswaran** [comment]
Closing as it seems that the question has been answered, thanks @air3ijai for helping out @fannyfan414 😄
