### ISSUE TITLE
Redis/RESP3 client proposed for inclusion in Boost

### ISSUE THREAD

**Issue by mzimbres** [Snapchat/KeyDB#546]
Sorry for opening an issue for this, I did not find any better means of contacting you.

I would like to invite your community to write a review for a C++ Redis client library that is being proposed for inclusion in Boost.

Your opinion as developers of KeyDB would be highly valuable. For more information see https://lists.boost.org/Archives/boost/2023/01/253871.php.

Thanks

**Comment by msotheeswaran** [comment]
Hi @mzimbres we will do a review, thanks for reaching out for our input!
