### ISSUE TITLE
[BUG] Build on Raspberry PI 4 fails again

### ISSUE THREAD

**Issue by Talkabout** [Snapchat/KeyDB#552]
Hi guys,

I tried to build v6.3.2 on my Raspberry PI 4 and again face an assertion issue:

`object.cpp: In function ‘char* serializeStoredStringObject(sds, robj_roptr)’:
object.cpp:1585:49: error: static assertion failed
 1585 |     static_assert((sizeof(robj) + sizeof(mvcc)) == sizeof(redisObjectStack), "");
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-atomic-alignment’ may have been intended to silence earlier diagnostics
make[1]: *** [Makefile:482: object.o] Fehler 1
make[1]: *** Es wird auf noch nicht beendete Prozesse gewartet....`

To reproduce simply try to build v6.3.2 on a Raspberry PI 4

I am trying to build on Debian 11 Bullseye.

Thanks!

**Comment by msotheeswaran** [comment]
Hi @Talkabout just want to confirm you are compiling for a 64 bit target, we are unlikely to continue supporting 32 bit, but if you are using 64 bit then we want to continue support. We don't see this issue on our 64 bit arm test machines, so this issue might be specific to Raspberry PI, unfortunately we don't have one to test with right now.

**Comment by Talkabout** [comment]
Hi @msotheeswaran ,

I am using a 32bit target. 64bit support and the corresponding images for Raspberry Pi 4 are quite recent and it is not that easy for me to migrate. If you plan to drop official support for 32bit arm, ok, but if it is still possible to at least "make it build" it'll be great.

Thanks!

Bye

**Comment by msotheeswaran** [comment]
Hi @Talkabout, if you are using 32 bit there may be other issues that we are not planning to support, but if you are simply looking to make it build, removing that assertion should unblock you.

**Comment by msotheeswaran** [comment]
Going to close this as there has been no update.
