### ISSUE TITLE
16 fixables vulnerabilities are present on eqalpha/keydb:x86_64_v6.3.2

### ISSUE THREAD

**Issue by YoranSys** [Snapchat/KeyDB#559]
## Request for Update Docker Image

I hope this message finds you well. I would like to use your image, but I have found multiple vulnerabilities on the latest version of the image on [ArtifactHub](https://artifacthub.io/packages/helm/enapter/keydb?modal=security-report).

There is 16 fixables vulnerabilities present on the latest image.

Could you please update the Docker image to fix these vulnerabilities?

Additionally, could I have access to the Dockerfile? I couldn't find it.

Thank you for your time and efforts.

![image](https://user-images.githubusercontent.com/11197007/216002084-0f6bc419-31ef-411a-8aca-845727b6f2b5.png)

![image](https://user-images.githubusercontent.com/11197007/216001923-5f78d987-7359-4903-ab2d-53430fdb21c6.png)

**Comment by sosan** [comment]
https://docs.keydb.dev/docs/dockerfiles/

**Comment by benschermel** [comment]
Thanks, we will take a look at this. The latest Dockerfiles are now located here: https://github.com/Snapchat/KeyDB/tree/main/pkg/docker 

The ones listed in that link are out of date. I have made an [issue](https://github.com/Snapchat/KeyDB-docs/issues/63) to update this document and link to the source Dockerfiles instead

**Comment by msotheeswaran** [comment]
We've updated our images to include the latest security fixes.
