### ISSUE TITLE
Need few clarifications regarding the Flash Storage 

### ISSUE THREAD

**Issue by Athinivas** [Snapchat/KeyDB#576]
Lets take my dataset is about ~200GB of data which doesn't fit in-memory & using Flash as storage provider, 
1) What will happen to the frequently queried keys in-memory after a restart (or) failure of the keyDB instance. 
2) Does KeyDB has any mechanism to restore the last accessed keys during the server startup (i.e cache warmup behavior).
3) If the cache warmup is based on access, is there way to override the default behavior to load the frequently accessed keys in memory using mmap ot sthng. during startup? 

Much Thanks, 
Athi

**Comment by msotheeswaran** [comment]
KeyDB will reload keys into memory from the storage provider on startup, there is no mechanism to determine which keys will be kept if there is not enough room in memory for all keys, so the keys will be evicted based on the configured eviction policy.

**Comment by Athinivas** [comment]
Thank you @msotheeswaran.
