### ISSUE TITLE
[BUG] EVAL crash after 6.2.2 => 6.3.0

### ISSUE THREAD

**Issue by ben-tilley-elw** [Snapchat/KeyDB#588]
**Describe the bug**

The following Lua code takes down the server after upgrading to 6.3.0. Atomically fetching the values of all keys matching a pattern.

```lua
local results = {}; for i,k in ipairs(redis.call('keys',ARGV[1])) do results[i] = redis.call('get',k) end; return results
```

**To reproduce**

1. Run a new keydb server.
1. Run `EVAL "local results = {}; for i,k in ipairs(redis.call('keys',ARGV[1])) do results[i] = redis.call('get',k) end; return results" 0 '*'
` on >= 6.3.0.

**Expected behavior**

Should return `(empty array)`. Or the values of all keys if there are any keys there. 🙏 

**Additional information**

Bug exists in all keydb versions >= 6.3.0.

KeyDB Bug report is same as https://github.com/Snapchat/KeyDB/issues/452.

**Comment by msotheeswaran** [comment]
Fixed with #564, keys command wasn't properly respecting the CLIENT_DENY_BLOCKING flag.
