### ISSUE TITLE
Evicted_keys always 0 if storage-provider enable

### ISSUE THREAD

**Issue by CrazyTennisFan** [Snapchat/KeyDB#602]
I found, if the storage-provider is enable in the config file, the evict_key always 0, I am not sure if this is a bug.
Even the maxmemory is reached.

Following is details：

Test command:

./memtier_benchmark -s 127.0.01 -p 6381 -t 10 -c 100 -n 10000000000 -d 506 --key-minimum=1 --key-maximum=10000000000 --ratio 1:0 --key-pattern=P:P

Test config file:

bind 127.0.01
port 6381
protected-mode no
notify-keyspace-events Ex
tcp-keepalive 30
timeout 0
maxmemory 8589934592
maxclients 10010
save ""
unixsocket /tmp/keydb.sock
unixsocketperm 600
client-output-buffer-limit slave 2147483648 2147483648 60
tcp-backlog 10000
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes
slave-lazy-flush yes
rdbcompression no
databases 16
appendonly no
appendfilename appendonly.aof
appendfsync no
no-appendfsync-on-rewrite yes
auto-aof-rewrite-percentage 0
lazyfree-lazy-user-flush yes
maxmemory-policy allkeys-lru
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
latency-monitor-threshold 0
repl-backlog-size 3221225472
repl-backlog-ttl 3600
slowlog-log-slower-than 10000
slowlog-max-len 128
storage-provider flash /home/ubuntu/keydb-pro-6/data

# Memory		
**used_memory:9885196344		
used_memory_human:9.21G		
used_memory_rss:10281250816**		
used_memory_rss_human:9.58G		
used_memory_peak:9960388632		
used_memory_peak_human:9.28G		
used_memory_peak_perc:99.25%		
used_memory_overhead:836745874		
used_memory_startup:5986312		
used_memory_dataset:9048450470		
used_memory_dataset_perc:91.59%		
allocator_allocated:9889408792		
allocator_active:9995661312		
allocator_resident:10351935488		
total_system_memory:16777809920		
total_system_memory_human:15.63G		
used_memory_lua:37888		
used_memory_lua_human:37.00K		
used_memory_scripts:0		
used_memory_scripts_human:0B		
number_of_cached_scripts:0		
**maxmemory:8589934592		
maxmemory_human:8.00G		
maxmemory_policy:allkeys-lru**		
allocator_frag_ratio:1.01		
allocator_frag_bytes:106252520		
allocator_rss_ratio:1.04		
allocator_rss_bytes:356274176		
rss_overhead_ratio:0.99		
rss_overhead_bytes:-70684672		
mem_fragmentation_ratio:1.04		
mem_fragmentation_bytes:395320128		
mem_not_counted_for_evict:1073741824		
mem_replication_backlog:0		
mem_clients_slaves:0		
mem_clients_normal:20752706		
mem_aof_buffer:0		
mem_allocator:jemalloc-5.2.1		
active_defrag_running:0		
lazyfree_pending_objects:0		
lazyfreed_objects:0		
storage_provider:flash		
flash_memory:9289281434		
		
# Stats		
total_connections_received:1001		
total_commands_processed:16894744		
instantaneous_ops_per_sec:16849		
total_net_input_bytes:9324024476		
total_net_output_bytes:84540982		
instantaneous_input_kbps:9024.41		
instantaneous_output_kbps:82.06		
rejected_connections:0		
sync_full:0		
sync_partial_ok:0		
sync_partial_err:0		
expired_keys:0		
expired_stale_perc:0.00		
expired_time_cap_reached_count:0		
expire_cycle_cpu_milliseconds:0		
**evicted_keys:0**		
keyspace_hits:0		
keyspace_misses:0		
pubsub_channels:0		
pubsub_patterns:0		
latest_fork_usec:0		
total_forks:0		
migrate_cached_sockets:0		
slave_expires_tracked_keys:0		
active_defrag_hits:0		
active_defrag_misses:0		
active_defrag_key_hits:0		
active_defrag_key_misses:0		
tracking_total_keys:0		
tracking_total_items:0		
tracking_total_prefixes:0		
unexpected_error_replies:0		
total_error_replies:0		
dump_payload_sanitizations:0		
total_reads_processed:16894849		
total_writes_processed:16894661		
instantaneous_lock_contention:5		
avg_lock_contention:4.765625		
storage_provider_read_hits:11		
storage_provider_read_misses:1621920		
		
# Keyspace		
db0:keys=16894728,expires=0,avg_ttl=0,cached_keys=15120595

**Comment by msotheeswaran** [comment]
Fixed by #621, thanks @CrazyTennisFan for finding and fixing the issue!
