### ISSUE TITLE
[BUG] Keydb failed to start if `db-s3-object` option is configured.

### ISSUE THREAD

**Issue by bijairimi** [Snapchat/KeyDB#623]
**Describe the bug**

Keydb failed to start if `db-s3-object` option is configured in the `keydb.conf`. The following error is reported in journalctl log:

keydb version: 6.3.2

```
*** FATAL CONFIG FILE ERROR (KeyDB 6.3.2) ***
Reading the configuration file, at line 2083
>>> 'db-s3-object s3://my-bucket/mybackup.rdb'
Bad directive or wrong number of arguments
```
The db-s3-object is configured as below in the keydb.conf:
```
db-s3-object s3://my-backup-bucket/keydb-backup.rdb aws-region my-aws-access-key my-aws-secret-key
```
also tried the following, as documented in the keydb documentation page:
```
db-s3-object s3://my-backup-bucket/keydb-backup.rdb
```
In addition, there is very little information concerning db-s3-object in the official keydb documentation page https://docs.keydb.dev/docs/intro-admin/

**To reproduce**

Add the following line to the keydb config file:

```
db-s3-object s3://my-backup-bucket/keydb-backup.rdb aws-region my-aws-access-key my-aws-secret-key
```
and then restart the keydb service.

**Expected behavior**

Keydb service should not fail to start and database backup file should automatically be backed up to s3 bucket.

**Comment by msotheeswaran** [comment]
That config wasn't in v6.3.2 added with #591
