### ISSUE TITLE
[BUG] swapdb issue

### ISSUE THREAD

**Issue by hengku** [Snapchat/KeyDB#626]
**Describe the bug**

swapdb command doesn't work as expected as Redis. 

**To reproduce**

1) start keydb with empty database

2) select 0 --- ok

3) set k1 v1 --- ok

4) swapdb 0 1 --- ok

5) get k1 --- v1 **(expected result should be nil instead of v1)**

6) select 1 --- ok

7) get k1 --- v1

8) select 0 --- ok

9) get k1 --- nil

**Expected behavior**

As step 5 described above.

**Additional information**

A fix was raised as PR #620

**Comment by msotheeswaran** [comment]
Merged fix  #620
