### ISSUE TITLE
[New KeyDB Conf] Add a configuration to disable the keycache (or storage cache) upfront

### ISSUE THREAD

**Issue by karthyuom** [Snapchat/KeyDB#642]
**The problem/use-case that the feature addresses**
Currently KeyDB maintains a keycache (or storage cache) for performance gains that provides caching functionality for the storage provider (e.g., rocksdb). As per the current behavior it still keeps entire key space even after the respective values are evicted from caching layer. We understood that due to the following reasons (or in special cases), we might not necessarily need keycache:
1. If we have scenarios where we need to deal with the large keys, it is possible that keycache might still lead the memory usage to hit the `maxmemory` and eventually it forces the keycache to disable on the fly inside the eviction logic
2. If we have flash enabled and underlying storage provider is SSD, we may still have the acceptable performance without the keycache
3. In the KeyDB cluster setup, especially in the slot migration use cases, we should make sure keycache is consistent across different shards/nodes for the data consistency purpose

Therefore, it is preferred to have a configuration (_keydb.conf_) that can help to disable the keycache upfront in the above scenarios.

**Description of the feature**
Introduce a new boolean configuration in the _keydb.conf_ which can help to disable the keycache upfront.

**Alternatives you've considered**
N/A.

**Additional information**
N/A.

 @paulmchen @yzhao244

**Comment by paulmchen** [comment]
@msotheeswaran @JohnSully  Hi Malavan and John, according to our discussion on Wednesday, could you please provide a configuration option that would disable the "key cache" feature. Our SSD use case has limited server memory, so disabling it upfront makes sense. Thank you.

**Comment by paulmchen** [comment]
@msotheeswaran  Thank you.
