### ISSUE TITLE
[BUG] Many OOM messages being sent to clients in FLASH storage for cluster mode

### ISSUE THREAD

**Issue by yzhao244** [Snapchat/KeyDB#646]
**Describe the bug**
After enabling FLASH storage option in cluster mode, for the use case of using a fairly small maxmemory for cost saving to serve tremendous amount of data,  clients side starts to see more and more OOM message being sent as more and more data being written to the cluster. 
![image](https://user-images.githubusercontent.com/15642771/235212705-6115de57-b957-423b-adf9-38b07b90fffa.png)
Eventually, it leads to Many OOM message which looks writing to the cluster becomes quite impossible. 
![image](https://user-images.githubusercontent.com/15642771/235214954-a41fe4c8-cf8a-4ba7-967d-89e5ac2f61d7.png)

Additionally, the number of cache keys in memory becomes less and less as more and more data being written to the cluster which I suspect maybe some data object in memory keeps growing and does not get evicted.
![image](https://user-images.githubusercontent.com/15642771/235213943-c77bf966-a91e-429f-8296-8dd849e52867.png)

![image](https://user-images.githubusercontent.com/15642771/235213825-cd960f4b-fb23-46b7-b162-eeffc3a4bd39.png)

By looking into the eviction codepath for storage, the eviction logic only removes the cached value but the keys in g_pserver->cluster->slots_to_keys data object is not evicted at all.
Therefore, theoretically speaking, if infinite amount of data written to the cluster with storage option, the g_pserver->cluster->slots_to_key data object could grow up infinitely and at some point will consume all the maxmemory which makes eviction logic have pretty much nothing to evict and fail with OOM. 

```
if (fEvictToStorage)
            {
                // This key is in the storage so we only need to free the object
                dictEntry *deT;
                if (db->removeCachedValue(bestkey, &deT)) {
                    mem_freed += splazy->addEntry(db->dictUnsafeKeyOnly(), deT);
                    ckeysFailed = 0;
                }
                else {
                    delta = 0;
                    ckeysFailed++;
                    if (ckeysFailed > 1024)
                        goto cant_free;
                }
            }
```

A short description of the bug.

**To reproduce**

This can be reproduced by starting keydb cluster and enable FLASH storage option, with a small maxmemory such as 1GB for more quickly reproducing the issue.
1. Run memtier to load many data such as the following.
2. At some point, many OOM being sent to clients so client cannot quite write to the cluster anymore

```
memtier_benchmark -s host -p port-t 50 -c 8 -n 800000 -d 256 --key-minimum=1 --key-maximum=320000000 --ratio 1:0 --key-pattern=P:P --hide-histogram --cluster-mode
```

Steps to reproduce the behavior and/or a minimal code sample.

**Expected behavior**

g_pserver->cluster->slots_to_keys should be properly handled as part of the eviction logic such as saving to disk, removing it as part of removecachedvalue logic or any other way because slots_to_keys data object can theoretically consume up all the memory and make cluster not functional well. 

**Additional information**

Any additional information that is relevant to the problem.

**Comment by yzhao244** [comment]
@paulmchen @hengku

**Comment by paulmchen** [comment]
@JohnSully @msotheeswaran  Hi John and Malavan, could you please help take a look at this issue, it is related to slots_to_keys data structure could keep growing and cause OOM due to keys in the data structure are never removed in a cluster enabled mode for SSD use case. Thanks.
