### ISSUE TITLE
[NEW] helm chart for master-master KeyDB

### ISSUE THREAD

**Issue by Antiarchitect** [Snapchat/KeyDB#669]
Hi, I'm the author of https://artifacthub.io/packages/helm/enapter/keydb chart and now I don't have much time to conduct it by myself. Are KeyDB is interested in taking it under the wing? Currently the code is located here: https://github.com/Enapter/charts and the license is MIT. I could help with the adoption but it is unlikely that I will take an active part in further development.

**Comment by neilclark-bgn** [comment]
I currently use this chart in several production Kubernetes clusters. Would love to see it get adopted as it's a very useful chart and I can see a lot of value in KeyDB offering an official Helm chart.

**Comment by msotheeswaran-sc** [comment]
Unfortunately we don't have the bandwidth to continue supporting this at Snap, we may be able to revisit an official helm chart in the future but not for now.

**Comment by SergkeiM** [comment]
Hi @msotheeswaran-sc 

Anything changed at Snap on the matter?

**Comment by SergkeiM** [comment]
Bitnami released a KeyDB chart https://github.com/bitnami/charts/pull/29025
