### ISSUE TITLE
[New] Batch Read feature

### ISSUE THREAD

**Issue by tronglamitmo142** [Snapchat/KeyDB#670]
Hi team! 

I have a concern that would be nice if you can explain it to me. 

I'm working on the benchmarking task of KeyDB Flash, using memtier. My requirement is 2TB of data, 3k batch read, the size of key = 1kb, and the size of value >= 3 MB. 
I already wrote the script that imports 10GB of data into Keydb Flash.
This is my KeyDB Flash command:
`keydb-server --storage-provider flash /mnt/myssd/ --maxmemory 15GB  --maxmemory-policy allkeys-lru`

But I have some concerns that I can't find anywhere:
1. Does KeyDB support batch read? 
2. If has, How can I benchmark the batch read with the key in my KeyDB? 

Thanks.

**Comment by msotheeswaran** [comment]
1. Yes KeyDB has mget command: https://docs.keydb.dev/docs/commands/#mget
2. You can use memtier_benchmark's custom command feature to benchmark your command: https://github.com/RedisLabs/memtier_benchmark

**Comment by tronglamitmo142** [comment]
Thanks for your helping!
