### ISSUE TITLE
RESP3 Null values

### ISSUE THREAD

**Issue by Coachonko** [Snapchat/KeyDB#697]
I am writing a KeyDB client library for the V language, I have noticed that KeyDB is currently responding with RESP2 `$-1\r\n` and `*-1\r\n` instead of using RESP3 `_\r\n`. 

Is KeyDB going to switch to RESP3 protocol or is it going to stay on RESP2?

**Comment by msotheeswaran-sc** [comment]
Each connection needs to manually let the server know it speaks RESP 3 by sending: 
`HELLO 3`
The default behaviour is to use RESP 2

**Comment by Coachonko** [comment]
The HELLO command seems to be missing form the docs. Am I wrong?
