### ISSUE TITLE
[BUG] Difference between KeyDB and Redis parsing of set command, which breaks the go-redis SetArgs function

### ISSUE THREAD

**Issue by einar-pexip** [Snapchat/KeyDB#711]
**Describe the bug**

If you use the go-redis library (https://github.com/redis/go-redis), and use it's SetArgs (https://pkg.go.dev/github.com/go-redis/redis/v9#Client.SetArgs) command with Mode NX, a TTL and Get set to true, then KeyDB fails with a syntax error. But this does not happen when using the Redis server instead of KeyDB.

**To reproduce**

The following code works with Redis and fails with KeyDB

```go
package main

import (
	"context"
	"errors"
	"fmt"
	"github.com/redis/go-redis/v9"
	"time"
)

func main() {
	ctx := context.Background()
	client := redis.NewClient(&redis.Options{})
	err := client.SetArgs(ctx, "test_key", "test_value", redis.SetArgs{Mode: "NX", TTL: time.Second, Get: true}).Err()
	if err != nil && !errors.Is(err, redis.Nil) {
		panic(fmt.Sprintf("Failed to run SetArgs %+v", err))
	}
}
```

to use the code. First make sure you have Go installed, create an empty dir, and add the code to main.go in it. After that run `go mod init github.com/redis/go-redis && go get github.com/redis/go-redis` in the dir to setup Go. Make sure you have a running KeyDB that listens to the default port on localhost,  and then do `go run main.go` to run the code.  

**Expected behavior**

A set statement that works in Redis, should imo. also work in KeyDB. 

**Additional information**

For testing this I used the eqalpha/keydb:x86_64_v6.3.3 docker image for KeyDB, redis:7.2.0 for the comparison Redis, and v9.1.0 of the go-redis library.

**Comment by msotheeswaran-sc** [comment]
From redis docs "Starting with Redis version 7.0.0: Allowed the NX and GET options to be used together."
KeyDB version 6 is only compatible with redis version 6, so this behaviour is not yet supported.
