### ISSUE TITLE
[Question] Cross Compiling

### ISSUE THREAD

**Issue by Talkabout** [Snapchat/KeyDB#719]
Hi guys,

is there a way to cross compile keydb on a x86_64 linux for arm 32bit?

Thanks!

**Comment by msotheeswaran-sc** [comment]
If you have a C and C++ cross compiler for x86_64 linux to arm 32bit, you can try building keydb replacing CC env variable with your C cross compiler and CXX env variable with your C++ cross compiler.

**Comment by Talkabout** [comment]
Hi @msotheeswaran-sc ,

tried that, thanks for the hint. Unfortunately I am facing issues on linking:

![image](https://github.com/Snapchat/KeyDB/assets/10157917/e7056165-0be5-404c-ad85-fb9ddc20cb54)

Any idea what could be wrong?

Thanks!

**Comment by Talkabout** [comment]
That's the point, there is no error:

`root@Stork:~/keydb# make clean
cd src && make clean
make[1]: Entering directory '/root/keydb/src'
rm -rf keydb-server keydb-sentinel keydb-cli keydb-benchmark keydb-check-rdb keydb-check-aof keydb-diagnostic-tool *.o *.gcda *.gcno *.gcov KeyDB.info lcov-html Makefile.dep
rm -rf storage/*.o
rm -rf keydb-server
rm -f adlist.d quicklist.d ae.d anet.d dict.d server.d sds.d zmalloc.d lzf_c.d lzf_d.d pqsort.d zipmap.d sha1.d ziplist.d release.d networking.d util.d object.d db.d replication.d rdb.d t_string.d t_list.d t_set.d t_zset.d t_hash.d t_nhash.d config.d aof.d pubsub.d multi.d debug.d sort.d intset.d syncio.d cluster.d crc16.d endianconv.d slowlog.d scripting.d bio.d rio.d rand.d memtest.d crcspeed.d crc64.d bitops.d sentinel.d notify.d setproctitle.d blocked.d hyperloglog.d latency.d sparkline.d redis-check-rdb.d redis-check-aof.d geo.d lazyfree.d module.d evict.d expire.d geohash.d geohash_helper.d childinfo.d defrag.d siphash.d rax.d t_stream.d listpack.d localtime.d acl.d storage.d rdb-s3.d fastlock.d new.d tracking.d cron.d connection.d tls.d sha256.d motd_server.d timeout.d setcpuaffinity.d AsyncWorkQueue.d snapshot.d storage/teststorageprovider.d keydbutils.d StorageCache.d monotonic.d cli_common.d mt19937-64.d meminfo.d fastlock_x64.d SnapshotPayloadParseState.d anet.d adlist.d dict.d redis-cli.d redis-cli-cpphelper.d zmalloc.d release.d anet.d ae.d crcspeed.d crc64.d siphash.d crc16.d storage-lite.d fastlock.d motd_client.d monotonic.d cli_common.d mt19937-64.d fastlock_x64.d ae.d anet.d redis-benchmark.d adlist.d dict.d zmalloc.d release.d crcspeed.d crc64.d siphash.d redis-benchmark.d storage-lite.d fastlock.d new.d monotonic.d cli_common.d mt19937-64.d fastlock_x64.d
make[1]: Leaving directory '/root/keydb/src'
root@Stork:~/keydb# export CC=/usr/bin/arm-linux-gnueabihf-gcc-10 && export CXX=/usr/bin/arm-linux-gnueabihf-g++-10 && make USE_SYSTEMD=yes
cd src && make all
make[1]: Entering directory '/root/keydb/src'
    CC Makefile.dep
    CC adlist.o
    CC quicklist.o
    CC ae.o
    CC anet.o
    CC dict.o
    CC server.o
server.cpp: In function 'char* genRedisInfoString(const char*)':
server.cpp:5750:51: warning: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'size_t' {aka 'unsigned int'} [-Wformat=]
 5750 |             snprintf(available_system_mem, 64, "%lu", g_pserver->cron_malloc_stats.sys_available);
      |                                                 ~~^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                   |                                |
      |                                                   long unsigned int                size_t {aka unsigned int}
      |                                                 %u
server.cpp: At top level:
cc1plus: note: unrecognized command-line option '-Wno-atomic-alignment' may have been intended to silence earlier diagnostics
    CC sds.o
    CC zmalloc.o
    CC lzf_c.o
    CC lzf_d.o
    CC pqsort.o
    CC zipmap.o
    CC sha1.o
    CC ziplist.o
    CC release.o
    CC networking.o
    CC util.o
    CC object.o
    CC db.o
    CC replication.o
    CC rdb.o
    CC t_string.o
    CC t_list.o
    CC t_set.o
    CC t_zset.o
    CC t_hash.o
    CC t_nhash.o
    CC config.o
    CC aof.o
    CC pubsub.o
    CC multi.o
    CC debug.o
    CC sort.o
    CC intset.o
    CC syncio.o
    CC cluster.o
    CC crc16.o
    CC endianconv.o
    CC slowlog.o
    CC scripting.o
    CC bio.o
    CC rio.o
    CC rand.o
    CC memtest.o
    CC crcspeed.o
    CC crc64.o
    CC bitops.o
bitops.cpp: In function 'void bitopCommand(client*)':
bitops.cpp:743:27: warning: unused variable 'i' [-Wunused-variable]
  743 |             unsigned long i;
      |                           ^
bitops.cpp: At top level:
cc1plus: note: unrecognized command-line option '-Wno-atomic-alignment' may have been intended to silence earlier diagnostics
    CC sentinel.o
    CC notify.o
    CC setproctitle.o
    CC blocked.o
    CC hyperloglog.o
    CC latency.o
    CC sparkline.o
    CC redis-check-rdb.o
    CC redis-check-aof.o
    CC geo.o
    CC lazyfree.o
    CC module.o
    CC evict.o
    CC expire.o
    CC geohash.o
    CC geohash_helper.o
    CC childinfo.o
    CC defrag.o
    CC siphash.o
    CC rax.o
    CC t_stream.o
    CC listpack.o
    CC localtime.o
    CC acl.o
    CC storage.o
    CC rdb-s3.o
    CC fastlock.o
    CC new.o
    CC tracking.o
    CC cron.o
    CC connection.o
    CC tls.o
    CC sha256.o
    CC motd_server.o
    CC timeout.o
    CC setcpuaffinity.o
    CC AsyncWorkQueue.o
    CC snapshot.o
In file included from snapshot.cpp:1:
snapshot.cpp: In member function 'bool redisDbPersistentDataSnapshot::iterate_threadsafe_core(std::function<bool(const char*, robj_roptr)>&, bool, bool, bool) const':
snapshot.cpp:632:31: warning: format '%ld' expects argument of type 'long int', but argument 3 has type 'int' [-Wformat=]
  632 |         serverLog(LL_WARNING, "celem: %ld", celem);
      |                               ^~~~~~~~~~~~  ~~~~~
      |                                             |
      |                                             int
server.h:4013:27: note: in definition of macro 'serverLog'
 4013 |         _serverLog(level, __VA_ARGS__);\
      |                           ^~~~~~~~~~~
snapshot.cpp:632:41: note: format string is defined here
  632 |         serverLog(LL_WARNING, "celem: %ld", celem);
      |                                       ~~^
      |                                         |
      |                                         long int
      |                                       %d
snapshot.cpp: At top level:
cc1plus: note: unrecognized command-line option '-Wno-atomic-alignment' may have been intended to silence earlier diagnostics
    CC storage/teststorageprovider.o
    CC keydbutils.o
    CC StorageCache.o
    CC monotonic.o
    CC cli_common.o
    CC mt19937-64.o
    CC meminfo.o
    CC fastlock_x64.o
    CC SnapshotPayloadParseState.o
    LINK keydb-server
arm-linux-gnueabihf-g++-10: error: ../deps/lua/src/liblua.a: No such file or directory
arm-linux-gnueabihf-g++-10: error: ../deps/jemalloc/lib/libjemalloc.a: No such file or directory
arm-linux-gnueabihf-g++-10: error: ../deps/hiredis/libhiredis_ssl.a: No such file or directory
make[1]: *** [Makefile:448: keydb-server] Error 1
make[1]: Leaving directory '/root/keydb/src'
make: *** [Makefile:6: all] Error 2`

**Comment by msotheeswaran-sc** [comment]
@Talkabout you need to use "make distclean" to reset deps folder and have the Makefile trigger, if that still does not work, you can try manually entering each directory and building them.

**Comment by Talkabout** [comment]
Hi @msotheeswaran-sc ,

one step ahead, thanks! :)

here is the error. I think this is related to the cross compiling I attempt to do:

![image](https://github.com/Snapchat/KeyDB/assets/10157917/8f80e358-c0a9-4405-af11-ed7c8565c22a)

Need to find out now how to pass the "--host" argument to the compiler.

Thanks! again for your help and support!

**Comment by msotheeswaran-sc** [comment]
Going to close this as the initial question seems to be resolved.
