### ISSUE TITLE
Is the project no longer in development?

### ISSUE THREAD

**Issue by ilyavaiser** [Snapchat/KeyDB#788]
The last release was in October, it contains issues affecting production. After half a year, the problems have not been fixed and it is unclear whether they will be fixed in the near future.

Is this project abandoned?

**Comment by silviucpp** [comment]
Last commits are one month ago in master .. so I doubt it's abandoned. Most probably they have other plans.
Anyway the active development was never so great..

**Comment by raphaelauv** [comment]
the main contributor https://github.com/Snapchat/KeyDB/commits?author=JohnSully

has no commit since 5 month and around 12 in 2023.

look like project is almost dead

**Comment by silviucpp** [comment]
@raphaelauv  @JohnSully  commited 3 days ago last time : https://github.com/Snapchat/KeyDB/pull/781

**Comment by JohnSully** [comment]
I think its clear the project doesn't have as much R&D as I would like.  However the database does run a significant percent of caching workloads at Snap and is in active use.  I do not get much time to go in and fix issues that we are not directly experiencing so I apologize if we haven't gotten to your bugs.

What we are working directly on right now is the FLASH feature.  The performance is quite bad of the existing implementation but with the work in the async_flash branch this should be rectified.

**Comment by ilyavaiser** [comment]
Please write that the project is not supported on the main page. People start using it and they suffer

**Comment by JohnSully** [comment]
@ilyavaiser  The project is in development.  Redis and Valkey exist as alternatives if that works better for you.
