### ISSUE TITLE
Please add/create a LICENSE file

### ISSUE THREAD

**Issue by jrconlin** [Snapchat/KeyDB#799]
With the recent change in Redis' license, it may be useful for groups and organizations if you added a discrete `LICENSE` file. This will help those folk quickly understand how they can use your code.

Here are a few options that may match how you wish to grant usage:
https://choosealicense.com/licenses/bsd-3-clause/

https://choosealicense.com/licenses/bsd-4-clause/

https://choosealicense.com/licenses/bsd-2-clause-patent/

(or see the chart at https://choosealicense.com/appendix/ for more options.)

Thanks!

**Comment by Jeder321** [comment]
there already is a COPYING file which is bsd-3

**Comment by elliotwutingfeng** [comment]
The COPYING file is already recognized by GitHub's license detector.

**Comment by JohnSully** [comment]
We are BSD 3. Always have been always will be.
