### ISSUE TITLE
Snap Inc mentioned as active contributor in new Linux Foundation backed Redis fork (Valkey)

### ISSUE THREAD

**Issue by dceravigupta** [Snapchat/KeyDB#812]
Wondering are there plans to merge/replace KeyDB with the newly announced Valkey in long run as Snap Inc is mentioned as a active contributor to that project? I can see the new community is super interested in modernizing Valkey(https://github.com/valkey-io/valkey/issues/17) which I guess was one of the primary reason for starting KeyDB.

https://www.linuxfoundation.org/press/linux-foundation-launches-open-source-valkey-community

**Comment by JohnSully** [comment]
We are interested in the new project but need to learn a bit more about its intended direction.  KeyDB runs critical Snap infrastructure and can’t be replaced by this project in its current form. 

We are continuing to implement a high performance FLASH implementation which will be included in the next release.
