### ISSUE TITLE
[BUG] Documentation and relevant Helm charts are out of date.

### ISSUE THREAD

**Issue by plsnotracking** [Snapchat/KeyDB#822]
**Describe the bug**

https://docs.keydb.dev/docs/download/ - the helm chart is not maintained since March 2023

- It leads to this repo on artifacthub.io - https://artifacthub.io/packages/helm/enapter/keydb
- Which leads to this GH repo - https://github.com/Enapter/charts which is now archived.

**To reproduce**

Visit website: https://artifacthub.io/packages/helm/enapter/keydb

**Expected behavior**

Have a more up to date Helm chart.

**Additional information**

No info, thanks a lot.

**Comment by ghost** [comment]
- #669

**Comment by plsnotracking** [comment]
https://github.com/Snapchat/KeyDB/issues/669#issuecomment-1714319925 - there's no bandwidth to support this atm as per author
